//#line 2 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the MST_Position package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __MST_Position__POSITION_PARAMSCONFIG_H__
#define __MST_Position__POSITION_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace MST_Position
{
  class Position_ParamsConfigStatics;
  
  class Position_ParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(Position_ParamsConfig &config, const Position_ParamsConfig &max, const Position_ParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const Position_ParamsConfig &config1, const Position_ParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, Position_ParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const Position_ParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Position_ParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const Position_ParamsConfig &config) const = 0;
      virtual void getValue(const Position_ParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T Position_ParamsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (Position_ParamsConfig::* field);

      virtual void clamp(Position_ParamsConfig &config, const Position_ParamsConfig &max, const Position_ParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const Position_ParamsConfig &config1, const Position_ParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, Position_ParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const Position_ParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Position_ParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const Position_ParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const Position_ParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, Position_ParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, Position_ParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<Position_ParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(Position_ParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("use_gpsd"==(*i)->name){use_gpsd = boost::any_cast<bool>(val);}
        if("continue_when_done"==(*i)->name){continue_when_done = boost::any_cast<bool>(val);}
        if("go_to_waypoints"==(*i)->name){go_to_waypoints = boost::any_cast<bool>(val);}
        if("waypoint_radius"==(*i)->name){waypoint_radius = boost::any_cast<double>(val);}
        if("dummy_point_radius"==(*i)->name){dummy_point_radius = boost::any_cast<double>(val);}
        if("reverse_order"==(*i)->name){reverse_order = boost::any_cast<bool>(val);}
        if("reset_waypoints"==(*i)->name){reset_waypoints = boost::any_cast<bool>(val);}
        if("skip_waypoint"==(*i)->name){skip_waypoint = boost::any_cast<bool>(val);}
        if("pause"==(*i)->name){pause = boost::any_cast<bool>(val);}
        if("heading_offset"==(*i)->name){heading_offset = boost::any_cast<double>(val);}
        if("use_dummy"==(*i)->name){use_dummy = boost::any_cast<bool>(val);}
        if("dummy_latitude"==(*i)->name){dummy_latitude = boost::any_cast<double>(val);}
        if("dummy_longitude"==(*i)->name){dummy_longitude = boost::any_cast<double>(val);}
        if("dummy_heading"==(*i)->name){dummy_heading = boost::any_cast<double>(val);}
        if("way_1_latitude"==(*i)->name){way_1_latitude = boost::any_cast<double>(val);}
        if("way_1_longitude"==(*i)->name){way_1_longitude = boost::any_cast<double>(val);}
        if("way_1_priority"==(*i)->name){way_1_priority = boost::any_cast<int>(val);}
        if("way_1_limit"==(*i)->name){way_1_limit = boost::any_cast<double>(val);}
        if("way_2_latitude"==(*i)->name){way_2_latitude = boost::any_cast<double>(val);}
        if("way_2_longitude"==(*i)->name){way_2_longitude = boost::any_cast<double>(val);}
        if("way_2_priority"==(*i)->name){way_2_priority = boost::any_cast<int>(val);}
        if("way_2_limit"==(*i)->name){way_2_limit = boost::any_cast<double>(val);}
        if("way_3_latitude"==(*i)->name){way_3_latitude = boost::any_cast<double>(val);}
        if("way_3_longitude"==(*i)->name){way_3_longitude = boost::any_cast<double>(val);}
        if("way_3_priority"==(*i)->name){way_3_priority = boost::any_cast<int>(val);}
        if("way_3_limit"==(*i)->name){way_3_limit = boost::any_cast<double>(val);}
        if("way_4_latitude"==(*i)->name){way_4_latitude = boost::any_cast<double>(val);}
        if("way_4_longitude"==(*i)->name){way_4_longitude = boost::any_cast<double>(val);}
        if("way_4_priority"==(*i)->name){way_4_priority = boost::any_cast<int>(val);}
        if("way_4_limit"==(*i)->name){way_4_limit = boost::any_cast<double>(val);}
        if("way_5_latitude"==(*i)->name){way_5_latitude = boost::any_cast<double>(val);}
        if("way_5_longitude"==(*i)->name){way_5_longitude = boost::any_cast<double>(val);}
        if("way_5_priority"==(*i)->name){way_5_priority = boost::any_cast<int>(val);}
        if("way_5_limit"==(*i)->name){way_5_limit = boost::any_cast<double>(val);}
        if("way_6_latitude"==(*i)->name){way_6_latitude = boost::any_cast<double>(val);}
        if("way_6_longitude"==(*i)->name){way_6_longitude = boost::any_cast<double>(val);}
        if("way_6_priority"==(*i)->name){way_6_priority = boost::any_cast<int>(val);}
        if("way_6_limit"==(*i)->name){way_6_limit = boost::any_cast<double>(val);}
        if("way_7_latitude"==(*i)->name){way_7_latitude = boost::any_cast<double>(val);}
        if("way_7_longitude"==(*i)->name){way_7_longitude = boost::any_cast<double>(val);}
        if("way_7_priority"==(*i)->name){way_7_priority = boost::any_cast<int>(val);}
        if("way_7_limit"==(*i)->name){way_7_limit = boost::any_cast<double>(val);}
        if("way_8_latitude"==(*i)->name){way_8_latitude = boost::any_cast<double>(val);}
        if("way_8_longitude"==(*i)->name){way_8_longitude = boost::any_cast<double>(val);}
        if("way_8_priority"==(*i)->name){way_8_priority = boost::any_cast<int>(val);}
        if("way_8_limit"==(*i)->name){way_8_limit = boost::any_cast<double>(val);}
        if("way_9_latitude"==(*i)->name){way_9_latitude = boost::any_cast<double>(val);}
        if("way_9_longitude"==(*i)->name){way_9_longitude = boost::any_cast<double>(val);}
        if("way_9_priority"==(*i)->name){way_9_priority = boost::any_cast<int>(val);}
        if("way_9_limit"==(*i)->name){way_9_limit = boost::any_cast<double>(val);}
        if("way_10_latitude"==(*i)->name){way_10_latitude = boost::any_cast<double>(val);}
        if("way_10_longitude"==(*i)->name){way_10_longitude = boost::any_cast<double>(val);}
        if("way_10_priority"==(*i)->name){way_10_priority = boost::any_cast<int>(val);}
        if("way_10_limit"==(*i)->name){way_10_limit = boost::any_cast<double>(val);}
      }
    }

    bool use_gpsd;
bool continue_when_done;
bool go_to_waypoints;
double waypoint_radius;
double dummy_point_radius;
bool reverse_order;
bool reset_waypoints;
bool skip_waypoint;
bool pause;
double heading_offset;
bool use_dummy;
double dummy_latitude;
double dummy_longitude;
double dummy_heading;
double way_1_latitude;
double way_1_longitude;
int way_1_priority;
double way_1_limit;
double way_2_latitude;
double way_2_longitude;
int way_2_priority;
double way_2_limit;
double way_3_latitude;
double way_3_longitude;
int way_3_priority;
double way_3_limit;
double way_4_latitude;
double way_4_longitude;
int way_4_priority;
double way_4_limit;
double way_5_latitude;
double way_5_longitude;
int way_5_priority;
double way_5_limit;
double way_6_latitude;
double way_6_longitude;
int way_6_priority;
double way_6_limit;
double way_7_latitude;
double way_7_longitude;
int way_7_priority;
double way_7_limit;
double way_8_latitude;
double way_8_longitude;
int way_8_priority;
double way_8_limit;
double way_9_latitude;
double way_9_longitude;
int way_9_priority;
double way_9_limit;
double way_10_latitude;
double way_10_longitude;
int way_10_priority;
double way_10_limit;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool use_gpsd;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool continue_when_done;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool go_to_waypoints;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double waypoint_radius;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double dummy_point_radius;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool reverse_order;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool reset_waypoints;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool skip_waypoint;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool pause;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double heading_offset;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool use_dummy;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double dummy_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double dummy_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double dummy_heading;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_1_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_1_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_1_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_1_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_2_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_2_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_2_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_2_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_3_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_3_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_3_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_3_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_4_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_4_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_4_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_4_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_5_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_5_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_5_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_5_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_6_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_6_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_6_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_6_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_7_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_7_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_7_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_7_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_8_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_8_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_8_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_8_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_9_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_9_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_9_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_9_limit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_10_latitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_10_longitude;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int way_10_priority;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double way_10_limit;
//#line 255 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("Position_ParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const Position_ParamsConfig &__max__ = __getMax__();
      const Position_ParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const Position_ParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const Position_ParamsConfig &__getDefault__();
    static const Position_ParamsConfig &__getMax__();
    static const Position_ParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const Position_ParamsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void Position_ParamsConfig::ParamDescription<std::string>::clamp(Position_ParamsConfig &config, const Position_ParamsConfig &max, const Position_ParamsConfig &min) const
  {
    return;
  }

  class Position_ParamsConfigStatics
  {
    friend class Position_ParamsConfig;
    
    Position_ParamsConfigStatics()
    {
Position_ParamsConfig::GroupDescription<Position_ParamsConfig::DEFAULT, Position_ParamsConfig> Default("Default", "", 0, 0, true, &Position_ParamsConfig::groups);
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.use_gpsd = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.use_gpsd = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.use_gpsd = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("use_gpsd", "bool", 1, "bool to use the garmin gps", "", &Position_ParamsConfig::use_gpsd)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("use_gpsd", "bool", 1, "bool to use the garmin gps", "", &Position_ParamsConfig::use_gpsd)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.continue_when_done = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.continue_when_done = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.continue_when_done = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("continue_when_done", "bool", 1, "bool to use the garmin gps", "", &Position_ParamsConfig::continue_when_done)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("continue_when_done", "bool", 1, "bool to use the garmin gps", "", &Position_ParamsConfig::continue_when_done)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.go_to_waypoints = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.go_to_waypoints = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.go_to_waypoints = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("go_to_waypoints", "bool", 1, "option to go forward or follow waypoints", "", &Position_ParamsConfig::go_to_waypoints)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("go_to_waypoints", "bool", 1, "option to go forward or follow waypoints", "", &Position_ParamsConfig::go_to_waypoints)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.waypoint_radius = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.waypoint_radius = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.waypoint_radius = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("waypoint_radius", "double", 1, "radius considerd to reach waypoints", "", &Position_ParamsConfig::waypoint_radius)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("waypoint_radius", "double", 1, "radius considerd to reach waypoints", "", &Position_ParamsConfig::waypoint_radius)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.dummy_point_radius = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.dummy_point_radius = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.dummy_point_radius = 3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_point_radius", "double", 1, "radius considerd to reach waypoints", "", &Position_ParamsConfig::dummy_point_radius)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_point_radius", "double", 1, "radius considerd to reach waypoints", "", &Position_ParamsConfig::dummy_point_radius)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.reverse_order = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.reverse_order = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.reverse_order = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("reverse_order", "bool", 1, "reverses order of movement", "", &Position_ParamsConfig::reverse_order)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("reverse_order", "bool", 1, "reverses order of movement", "", &Position_ParamsConfig::reverse_order)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.reset_waypoints = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.reset_waypoints = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.reset_waypoints = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("reset_waypoints", "bool", 1, "resets waypoint list to begining", "", &Position_ParamsConfig::reset_waypoints)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("reset_waypoints", "bool", 1, "resets waypoint list to begining", "", &Position_ParamsConfig::reset_waypoints)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.skip_waypoint = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.skip_waypoint = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.skip_waypoint = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("skip_waypoint", "bool", 1, "option to skip a waypoint", "", &Position_ParamsConfig::skip_waypoint)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("skip_waypoint", "bool", 1, "option to skip a waypoint", "", &Position_ParamsConfig::skip_waypoint)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.pause = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.pause = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.pause = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("pause", "bool", 1, "stops the robot and pauses waypoints", "", &Position_ParamsConfig::pause)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("pause", "bool", 1, "stops the robot and pauses waypoints", "", &Position_ParamsConfig::pause)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.heading_offset = -3.14159265359;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.heading_offset = 3.14159265359;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.heading_offset = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("heading_offset", "double", 1, "offset aplied to gps heading", "", &Position_ParamsConfig::heading_offset)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("heading_offset", "double", 1, "offset aplied to gps heading", "", &Position_ParamsConfig::heading_offset)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.use_dummy = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.use_dummy = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.use_dummy = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("use_dummy", "bool", 1, "option use dummy gps for testing", "", &Position_ParamsConfig::use_dummy)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<bool>("use_dummy", "bool", 1, "option use dummy gps for testing", "", &Position_ParamsConfig::use_dummy)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.dummy_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.dummy_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.dummy_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_latitude", "double", 1, "latitude for dummy gps", "", &Position_ParamsConfig::dummy_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_latitude", "double", 1, "latitude for dummy gps", "", &Position_ParamsConfig::dummy_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.dummy_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.dummy_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.dummy_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_longitude", "double", 1, "longitude for dummy gps", "", &Position_ParamsConfig::dummy_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_longitude", "double", 1, "longitude for dummy gps", "", &Position_ParamsConfig::dummy_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.dummy_heading = -3.14159265359;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.dummy_heading = 3.14159265359;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.dummy_heading = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_heading", "double", 1, "heading for dummy gps in radians", "", &Position_ParamsConfig::dummy_heading)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("dummy_heading", "double", 1, "heading for dummy gps in radians", "", &Position_ParamsConfig::dummy_heading)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_1_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_1_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_1_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_1_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_1_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_1_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_1_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_1_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_1_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_1_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_1_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_1_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_1_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_1_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_1_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_1_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_1_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_1_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_1_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_1_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_1_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_1_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_1_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_1_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_1_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_1_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_1_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_1_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_2_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_2_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_2_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_2_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_2_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_2_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_2_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_2_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_2_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_2_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_2_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_2_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_2_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_2_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_2_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_2_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_2_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_2_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_2_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_2_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_2_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_2_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_2_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_2_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_2_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_2_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_2_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_2_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_3_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_3_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_3_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_3_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_3_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_3_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_3_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_3_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_3_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_3_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_3_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_3_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_3_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_3_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_3_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_3_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_3_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_3_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_3_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_3_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_3_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_3_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_3_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_3_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_3_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_3_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_3_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_3_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_4_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_4_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_4_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_4_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_4_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_4_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_4_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_4_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_4_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_4_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_4_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_4_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_4_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_4_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_4_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_4_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_4_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_4_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_4_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_4_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_4_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_4_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_4_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_4_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_4_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_4_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_4_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_4_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_5_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_5_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_5_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_5_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_5_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_5_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_5_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_5_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_5_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_5_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_5_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_5_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_5_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_5_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_5_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_5_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_5_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_5_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_5_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_5_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_5_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_5_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_5_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_5_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_5_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_5_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_5_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_5_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_6_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_6_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_6_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_6_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_6_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_6_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_6_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_6_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_6_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_6_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_6_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_6_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_6_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_6_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_6_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_6_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_6_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_6_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_6_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_6_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_6_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_6_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_6_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_6_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_6_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_6_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_6_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_6_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_7_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_7_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_7_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_7_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_7_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_7_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_7_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_7_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_7_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_7_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_7_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_7_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_7_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_7_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_7_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_7_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_7_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_7_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_7_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_7_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_7_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_7_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_7_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_7_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_7_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_7_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_7_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_7_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_8_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_8_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_8_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_8_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_8_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_8_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_8_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_8_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_8_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_8_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_8_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_8_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_8_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_8_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_8_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_8_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_8_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_8_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_8_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_8_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_8_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_8_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_8_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_8_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_8_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_8_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_8_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_8_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_9_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_9_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_9_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_9_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_9_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_9_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_9_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_9_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_9_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_9_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_9_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_9_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_9_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_9_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_9_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_9_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_9_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_9_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_9_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_9_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_9_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_9_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_9_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_9_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_9_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_9_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_9_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_9_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_10_latitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_10_latitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_10_latitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_10_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_10_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_10_latitude", "double", 1, "latitude for waypoint", "", &Position_ParamsConfig::way_10_latitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_10_longitude = -90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_10_longitude = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_10_longitude = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_10_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_10_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_10_longitude", "double", 1, "longitude for waypoint", "", &Position_ParamsConfig::way_10_longitude)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_10_priority = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_10_priority = 10;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_10_priority = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_10_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_10_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<int>("way_10_priority", "int", 1, "priority of waypoint(0 is ignored)", "", &Position_ParamsConfig::way_10_priority)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.way_10_limit = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.way_10_limit = 90.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.way_10_limit = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_10_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_10_limit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(Position_ParamsConfig::AbstractParamDescriptionConstPtr(new Position_ParamsConfig::ParamDescription<double>("way_10_limit", "double", 1, "timelimit for waypoint(0 is ignored) in min", "", &Position_ParamsConfig::way_10_limit)));
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(Position_ParamsConfig::AbstractGroupDescriptionConstPtr(new Position_ParamsConfig::GroupDescription<Position_ParamsConfig::DEFAULT, Position_ParamsConfig>(Default)));
//#line 390 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<Position_ParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<Position_ParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<Position_ParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    Position_ParamsConfig __max__;
    Position_ParamsConfig __min__;
    Position_ParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const Position_ParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static Position_ParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &Position_ParamsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const Position_ParamsConfig &Position_ParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const Position_ParamsConfig &Position_ParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const Position_ParamsConfig &Position_ParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<Position_ParamsConfig::AbstractParamDescriptionConstPtr> &Position_ParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<Position_ParamsConfig::AbstractGroupDescriptionConstPtr> &Position_ParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const Position_ParamsConfigStatics *Position_ParamsConfig::__get_statics__()
  {
    const static Position_ParamsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = Position_ParamsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __POSITION_PARAMSRECONFIGURATOR_H__
