//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the mst_color package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __mst_color__COLOR_PARAMSCONFIG_H__
#define __mst_color__COLOR_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace mst_color
{
  class color_paramsConfigStatics;
  
  class color_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(color_paramsConfig &config, const color_paramsConfig &max, const color_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const color_paramsConfig &config1, const color_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, color_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const color_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, color_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const color_paramsConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T color_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (color_paramsConfig::* field);

      virtual void clamp(color_paramsConfig &config, const color_paramsConfig &max, const color_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const color_paramsConfig &config1, const color_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, color_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const color_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, color_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const color_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 22 "../cfg/color.cfg"
      int sobel_size;
//#line 23 "../cfg/color.cfg"
      int sobel_order;
//#line 24 "../cfg/color.cfg"
      double sobel_scaler;
//#line 25 "../cfg/color.cfg"
      double slope_var_thresh;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("color_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const color_paramsConfig &__max__ = __getMax__();
      const color_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const color_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const color_paramsConfig &__getDefault__();
    static const color_paramsConfig &__getMax__();
    static const color_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const color_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void color_paramsConfig::ParamDescription<std::string>::clamp(color_paramsConfig &config, const color_paramsConfig &max, const color_paramsConfig &min) const
  {
    return;
  }

  class color_paramsConfigStatics
  {
    friend class color_paramsConfig;
    
    color_paramsConfigStatics()
    {
//#line 22 "../cfg/color.cfg"
      __min__.sobel_size = -1;
//#line 22 "../cfg/color.cfg"
      __max__.sobel_size = 7;
//#line 22 "../cfg/color.cfg"
      __default__.sobel_size = 3;
//#line 22 "../cfg/color.cfg"
      __param_descriptions__.push_back(color_paramsConfig::AbstractParamDescriptionConstPtr(new color_paramsConfig::ParamDescription<int>("sobel_size", "int", 0, "The size value of the sobel filter slope finder", "{'enum_description': 'Size of sobel filter', 'enum': [{'srcline': 15, 'description': 'A 3x1 filter with no Gaussinan smoothing', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': '3x1'}, {'srcline': 16, 'description': 'A 3x3 sobel filter', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': '3x3'}, {'srcline': 17, 'description': 'A 5x5 sobel filter', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': '5x5'}, {'srcline': 18, 'description': 'A 7x7 sobel filter', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 7, 'ctype': 'int', 'type': 'int', 'name': '7x7'}]}", &color_paramsConfig::sobel_size)));
//#line 23 "../cfg/color.cfg"
      __min__.sobel_order = 1;
//#line 23 "../cfg/color.cfg"
      __max__.sobel_order = 2;
//#line 23 "../cfg/color.cfg"
      __default__.sobel_order = 1;
//#line 23 "../cfg/color.cfg"
      __param_descriptions__.push_back(color_paramsConfig::AbstractParamDescriptionConstPtr(new color_paramsConfig::ParamDescription<int>("sobel_order", "int", 0, "Value of the sobel filter order", "", &color_paramsConfig::sobel_order)));
//#line 24 "../cfg/color.cfg"
      __min__.sobel_scaler = 1.0;
//#line 24 "../cfg/color.cfg"
      __max__.sobel_scaler = 300.0;
//#line 24 "../cfg/color.cfg"
      __default__.sobel_scaler = 1.0;
//#line 24 "../cfg/color.cfg"
      __param_descriptions__.push_back(color_paramsConfig::AbstractParamDescriptionConstPtr(new color_paramsConfig::ParamDescription<double>("sobel_scaler", "double", 0, "Value multiplied to sobel", "", &color_paramsConfig::sobel_scaler)));
//#line 25 "../cfg/color.cfg"
      __min__.slope_var_thresh = 1.0;
//#line 25 "../cfg/color.cfg"
      __max__.slope_var_thresh = 300.0;
//#line 25 "../cfg/color.cfg"
      __default__.slope_var_thresh = 1.0;
//#line 25 "../cfg/color.cfg"
      __param_descriptions__.push_back(color_paramsConfig::AbstractParamDescriptionConstPtr(new color_paramsConfig::ParamDescription<double>("slope_var_thresh", "double", 0, "Value for maximum change in slope", "", &color_paramsConfig::slope_var_thresh)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<color_paramsConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<color_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    color_paramsConfig __max__;
    color_paramsConfig __min__;
    color_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const color_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static color_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &color_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const color_paramsConfig &color_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const color_paramsConfig &color_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const color_paramsConfig &color_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<color_paramsConfig::AbstractParamDescriptionConstPtr> &color_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const color_paramsConfigStatics *color_paramsConfig::__get_statics__()
  {
    const static color_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = color_paramsConfigStatics::get_instance();
    
    return statics;
  }

//#line 15 "../cfg/color.cfg"
      const int color_params_3x1 = 1;
//#line 16 "../cfg/color.cfg"
      const int color_params_3x3 = 3;
//#line 17 "../cfg/color.cfg"
      const int color_params_5x5 = 5;
//#line 18 "../cfg/color.cfg"
      const int color_params_7x7 = 7;
}

#endif // __COLOR_PARAMSRECONFIGURATOR_H__
