"""autogenerated by genmsg_py from JAUS_out.msg. Do not edit."""
import roslib.message
import struct


class JAUS_out(roslib.message.Message):
  _md5sum = "7e012a56e7a3ad7208d1282bc8555c2e"
  _type = "MST_JAUS/JAUS_out"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool        request_control
bool        request_resume
bool        request_standby
bool        request_shutdown

"""
  __slots__ = ['request_control','request_resume','request_standby','request_shutdown']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       request_control,request_resume,request_standby,request_shutdown
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(JAUS_out, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.request_control is None:
        self.request_control = False
      if self.request_resume is None:
        self.request_resume = False
      if self.request_standby is None:
        self.request_standby = False
      if self.request_shutdown is None:
        self.request_shutdown = False
    else:
      self.request_control = False
      self.request_resume = False
      self.request_standby = False
      self.request_shutdown = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.request_control, _x.request_resume, _x.request_standby, _x.request_shutdown))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.request_control, _x.request_resume, _x.request_standby, _x.request_shutdown,) = _struct_4B.unpack(str[start:end])
      self.request_control = bool(self.request_control)
      self.request_resume = bool(self.request_resume)
      self.request_standby = bool(self.request_standby)
      self.request_shutdown = bool(self.request_shutdown)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.request_control, _x.request_resume, _x.request_standby, _x.request_shutdown))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.request_control, _x.request_resume, _x.request_standby, _x.request_shutdown,) = _struct_4B.unpack(str[start:end])
      self.request_control = bool(self.request_control)
      self.request_resume = bool(self.request_resume)
      self.request_standby = bool(self.request_standby)
      self.request_shutdown = bool(self.request_shutdown)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_4B = struct.Struct("<4B")
