/* Auto-generated by genmsg_cpp for file /home/robot/Documents/Jomegatron_IGVC/mst_common/msg/ImageFilter.msg */
#ifndef MST_COMMON_MESSAGE_IMAGEFILTER_H
#define MST_COMMON_MESSAGE_IMAGEFILTER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "mst_common/Filter.h"

namespace mst_common
{
template <class ContainerAllocator>
struct ImageFilter_ {
  typedef ImageFilter_<ContainerAllocator> Type;

  ImageFilter_()
  : type()
  , filter()
  {
  }

  ImageFilter_(const ContainerAllocator& _alloc)
  : type(_alloc)
  , filter()
  {
    filter.assign( ::mst_common::Filter_<ContainerAllocator> (_alloc));
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  type;

  typedef boost::array< ::mst_common::Filter_<ContainerAllocator> , 3>  _filter_type;
  boost::array< ::mst_common::Filter_<ContainerAllocator> , 3>  filter;


  ROS_DEPRECATED uint32_t get_filter_size() const { return (uint32_t)filter.size(); }
private:
  static const char* __s_getDataType_() { return "mst_common/ImageFilter"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "fa622389d14d78c43b4f70337cbd1806"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string      type\n\
Filter[3]   filter\n\
\n\
================================================================================\n\
MSG: mst_common/Filter\n\
uint8[256]  gain\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, filter);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, filter);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(filter);
    return size;
  }

  typedef boost::shared_ptr< ::mst_common::ImageFilter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mst_common::ImageFilter_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ImageFilter
typedef  ::mst_common::ImageFilter_<std::allocator<void> > ImageFilter;

typedef boost::shared_ptr< ::mst_common::ImageFilter> ImageFilterPtr;
typedef boost::shared_ptr< ::mst_common::ImageFilter const> ImageFilterConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::mst_common::ImageFilter_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::mst_common::ImageFilter_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace mst_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mst_common::ImageFilter_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mst_common::ImageFilter_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mst_common::ImageFilter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fa622389d14d78c43b4f70337cbd1806";
  }

  static const char* value(const  ::mst_common::ImageFilter_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfa622389d14d78c4ULL;
  static const uint64_t static_value2 = 0x3b4f70337cbd1806ULL;
};

template<class ContainerAllocator>
struct DataType< ::mst_common::ImageFilter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mst_common/ImageFilter";
  }

  static const char* value(const  ::mst_common::ImageFilter_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mst_common::ImageFilter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string      type\n\
Filter[3]   filter\n\
\n\
================================================================================\n\
MSG: mst_common/Filter\n\
uint8[256]  gain\n\
\n\
";
  }

  static const char* value(const  ::mst_common::ImageFilter_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mst_common::ImageFilter_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.type);
    stream.next(m.filter);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ImageFilter_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mst_common::ImageFilter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::mst_common::ImageFilter_<ContainerAllocator> & v) 
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "filter[]" << std::endl;
    for (size_t i = 0; i < v.filter.size(); ++i)
    {
      s << indent << "  filter[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mst_common::Filter_<ContainerAllocator> >::stream(s, indent + "    ", v.filter[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // MST_COMMON_MESSAGE_IMAGEFILTER_H

