/* Auto-generated by genmsg_cpp for file /home/robot/Documents/MST_Broken/mst_common/msg/IMU.msg */
#ifndef MST_COMMON_MESSAGE_IMU_H
#define MST_COMMON_MESSAGE_IMU_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace mst_common
{
template <class ContainerAllocator>
struct IMU_ {
  typedef IMU_<ContainerAllocator> Type;

  IMU_()
  : latitude(0.0)
  , longitude(0.0)
  , altitude(0.0)
  , heading(0.0)
  , speed(0.0)
  , angular_rate(0.0)
  , gps_time(0.0)
  , position_valid(false)
  , heading_valid(false)
  , speed_valid(false)
  , angular_rate_valid(false)
  , position_accuracy(0.0)
  {
  }

  IMU_(const ContainerAllocator& _alloc)
  : latitude(0.0)
  , longitude(0.0)
  , altitude(0.0)
  , heading(0.0)
  , speed(0.0)
  , angular_rate(0.0)
  , gps_time(0.0)
  , position_valid(false)
  , heading_valid(false)
  , speed_valid(false)
  , angular_rate_valid(false)
  , position_accuracy(0.0)
  {
  }

  typedef double _latitude_type;
  double latitude;

  typedef double _longitude_type;
  double longitude;

  typedef double _altitude_type;
  double altitude;

  typedef double _heading_type;
  double heading;

  typedef double _speed_type;
  double speed;

  typedef double _angular_rate_type;
  double angular_rate;

  typedef double _gps_time_type;
  double gps_time;

  typedef uint8_t _position_valid_type;
  uint8_t position_valid;

  typedef uint8_t _heading_valid_type;
  uint8_t heading_valid;

  typedef uint8_t _speed_valid_type;
  uint8_t speed_valid;

  typedef uint8_t _angular_rate_valid_type;
  uint8_t angular_rate_valid;

  typedef double _position_accuracy_type;
  double position_accuracy;


private:
  static const char* __s_getDataType_() { return "mst_common/IMU"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "24a707f7b1bd25df70e9c37ca3771892"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64     latitude\n\
float64     longitude\n\
float64     altitude\n\
float64     heading\n\
float64     speed\n\
float64     angular_rate\n\
float64     gps_time\n\
bool        position_valid\n\
bool        heading_valid\n\
bool        speed_valid\n\
bool        angular_rate_valid\n\
float64     position_accuracy\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, latitude);
    ros::serialization::serialize(stream, longitude);
    ros::serialization::serialize(stream, altitude);
    ros::serialization::serialize(stream, heading);
    ros::serialization::serialize(stream, speed);
    ros::serialization::serialize(stream, angular_rate);
    ros::serialization::serialize(stream, gps_time);
    ros::serialization::serialize(stream, position_valid);
    ros::serialization::serialize(stream, heading_valid);
    ros::serialization::serialize(stream, speed_valid);
    ros::serialization::serialize(stream, angular_rate_valid);
    ros::serialization::serialize(stream, position_accuracy);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, latitude);
    ros::serialization::deserialize(stream, longitude);
    ros::serialization::deserialize(stream, altitude);
    ros::serialization::deserialize(stream, heading);
    ros::serialization::deserialize(stream, speed);
    ros::serialization::deserialize(stream, angular_rate);
    ros::serialization::deserialize(stream, gps_time);
    ros::serialization::deserialize(stream, position_valid);
    ros::serialization::deserialize(stream, heading_valid);
    ros::serialization::deserialize(stream, speed_valid);
    ros::serialization::deserialize(stream, angular_rate_valid);
    ros::serialization::deserialize(stream, position_accuracy);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(latitude);
    size += ros::serialization::serializationLength(longitude);
    size += ros::serialization::serializationLength(altitude);
    size += ros::serialization::serializationLength(heading);
    size += ros::serialization::serializationLength(speed);
    size += ros::serialization::serializationLength(angular_rate);
    size += ros::serialization::serializationLength(gps_time);
    size += ros::serialization::serializationLength(position_valid);
    size += ros::serialization::serializationLength(heading_valid);
    size += ros::serialization::serializationLength(speed_valid);
    size += ros::serialization::serializationLength(angular_rate_valid);
    size += ros::serialization::serializationLength(position_accuracy);
    return size;
  }

  typedef boost::shared_ptr< ::mst_common::IMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mst_common::IMU_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct IMU
typedef  ::mst_common::IMU_<std::allocator<void> > IMU;

typedef boost::shared_ptr< ::mst_common::IMU> IMUPtr;
typedef boost::shared_ptr< ::mst_common::IMU const> IMUConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::mst_common::IMU_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::mst_common::IMU_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace mst_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mst_common::IMU_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mst_common::IMU_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mst_common::IMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "24a707f7b1bd25df70e9c37ca3771892";
  }

  static const char* value(const  ::mst_common::IMU_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x24a707f7b1bd25dfULL;
  static const uint64_t static_value2 = 0x70e9c37ca3771892ULL;
};

template<class ContainerAllocator>
struct DataType< ::mst_common::IMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mst_common/IMU";
  }

  static const char* value(const  ::mst_common::IMU_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mst_common::IMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64     latitude\n\
float64     longitude\n\
float64     altitude\n\
float64     heading\n\
float64     speed\n\
float64     angular_rate\n\
float64     gps_time\n\
bool        position_valid\n\
bool        heading_valid\n\
bool        speed_valid\n\
bool        angular_rate_valid\n\
float64     position_accuracy\n\
\n\
";
  }

  static const char* value(const  ::mst_common::IMU_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mst_common::IMU_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mst_common::IMU_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.latitude);
    stream.next(m.longitude);
    stream.next(m.altitude);
    stream.next(m.heading);
    stream.next(m.speed);
    stream.next(m.angular_rate);
    stream.next(m.gps_time);
    stream.next(m.position_valid);
    stream.next(m.heading_valid);
    stream.next(m.speed_valid);
    stream.next(m.angular_rate_valid);
    stream.next(m.position_accuracy);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IMU_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mst_common::IMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::mst_common::IMU_<ContainerAllocator> & v) 
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "angular_rate: ";
    Printer<double>::stream(s, indent + "  ", v.angular_rate);
    s << indent << "gps_time: ";
    Printer<double>::stream(s, indent + "  ", v.gps_time);
    s << indent << "position_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_valid);
    s << indent << "heading_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.heading_valid);
    s << indent << "speed_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_valid);
    s << indent << "angular_rate_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.angular_rate_valid);
    s << indent << "position_accuracy: ";
    Printer<double>::stream(s, indent + "  ", v.position_accuracy);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MST_COMMON_MESSAGE_IMU_H

