/* Auto-generated by genmsg_cpp for file /home/robot/Documents/MST_Broken/mst_common/msg/VisionFilter.msg */
#ifndef MST_COMMON_MESSAGE_VISIONFILTER_H
#define MST_COMMON_MESSAGE_VISIONFILTER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "mst_common/ImageFilter.h"

namespace mst_common
{
template <class ContainerAllocator>
struct VisionFilter_ {
  typedef VisionFilter_<ContainerAllocator> Type;

  VisionFilter_()
  : header()
  , color()
  {
  }

  VisionFilter_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , color(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::mst_common::ImageFilter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mst_common::ImageFilter_<ContainerAllocator> >::other >  _color_type;
  std::vector< ::mst_common::ImageFilter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mst_common::ImageFilter_<ContainerAllocator> >::other >  color;


  ROS_DEPRECATED uint32_t get_color_size() const { return (uint32_t)color.size(); }
  ROS_DEPRECATED void set_color_size(uint32_t size) { color.resize((size_t)size); }
  ROS_DEPRECATED void get_color_vec(std::vector< ::mst_common::ImageFilter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mst_common::ImageFilter_<ContainerAllocator> >::other > & vec) const { vec = this->color; }
  ROS_DEPRECATED void set_color_vec(const std::vector< ::mst_common::ImageFilter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mst_common::ImageFilter_<ContainerAllocator> >::other > & vec) { this->color = vec; }
private:
  static const char* __s_getDataType_() { return "mst_common/VisionFilter"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "444ae704995b1a5f6fd91cb7494a14b0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header          header\n\
ImageFilter[]   color\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mst_common/ImageFilter\n\
string      type\n\
Filter[3]   filter\n\
\n\
================================================================================\n\
MSG: mst_common/Filter\n\
uint8[256]  gain\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, color);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, color);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(color);
    return size;
  }

  typedef boost::shared_ptr< ::mst_common::VisionFilter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mst_common::VisionFilter_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct VisionFilter
typedef  ::mst_common::VisionFilter_<std::allocator<void> > VisionFilter;

typedef boost::shared_ptr< ::mst_common::VisionFilter> VisionFilterPtr;
typedef boost::shared_ptr< ::mst_common::VisionFilter const> VisionFilterConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::mst_common::VisionFilter_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::mst_common::VisionFilter_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace mst_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mst_common::VisionFilter_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mst_common::VisionFilter_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mst_common::VisionFilter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "444ae704995b1a5f6fd91cb7494a14b0";
  }

  static const char* value(const  ::mst_common::VisionFilter_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x444ae704995b1a5fULL;
  static const uint64_t static_value2 = 0x6fd91cb7494a14b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mst_common::VisionFilter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mst_common/VisionFilter";
  }

  static const char* value(const  ::mst_common::VisionFilter_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mst_common::VisionFilter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header          header\n\
ImageFilter[]   color\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mst_common/ImageFilter\n\
string      type\n\
Filter[3]   filter\n\
\n\
================================================================================\n\
MSG: mst_common/Filter\n\
uint8[256]  gain\n\
\n\
";
  }

  static const char* value(const  ::mst_common::VisionFilter_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::mst_common::VisionFilter_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::mst_common::VisionFilter_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mst_common::VisionFilter_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.color);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VisionFilter_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mst_common::VisionFilter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::mst_common::VisionFilter_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mst_common::ImageFilter_<ContainerAllocator> >::stream(s, indent + "    ", v.color[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // MST_COMMON_MESSAGE_VISIONFILTER_H

