/* Auto-generated by genmsg_cpp for file /home/robot/Documents/Jomegatron_IGVC/MST_Position/msg/inital_gps.msg */
#ifndef MST_POSITION_MESSAGE_INITAL_GPS_H
#define MST_POSITION_MESSAGE_INITAL_GPS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace MST_Position
{
template <class ContainerAllocator>
struct inital_gps_ {
  typedef inital_gps_<ContainerAllocator> Type;

  inital_gps_()
  : target_heading(0.0)
  , distance(0.0)
  , waypoint(0.0)
  {
  }

  inital_gps_(const ContainerAllocator& _alloc)
  : target_heading(0.0)
  , distance(0.0)
  , waypoint(0.0)
  {
  }

  typedef double _target_heading_type;
  double target_heading;

  typedef double _distance_type;
  double distance;

  typedef double _waypoint_type;
  double waypoint;


private:
  static const char* __s_getDataType_() { return "MST_Position/inital_gps"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ba0fbfca81c6cac39788bbb65f584f05"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64     target_heading\n\
float64     distance\n\
float64     waypoint\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, target_heading);
    ros::serialization::serialize(stream, distance);
    ros::serialization::serialize(stream, waypoint);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, target_heading);
    ros::serialization::deserialize(stream, distance);
    ros::serialization::deserialize(stream, waypoint);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(target_heading);
    size += ros::serialization::serializationLength(distance);
    size += ros::serialization::serializationLength(waypoint);
    return size;
  }

  typedef boost::shared_ptr< ::MST_Position::inital_gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MST_Position::inital_gps_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct inital_gps
typedef  ::MST_Position::inital_gps_<std::allocator<void> > inital_gps;

typedef boost::shared_ptr< ::MST_Position::inital_gps> inital_gpsPtr;
typedef boost::shared_ptr< ::MST_Position::inital_gps const> inital_gpsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::MST_Position::inital_gps_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::MST_Position::inital_gps_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace MST_Position

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::MST_Position::inital_gps_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::MST_Position::inital_gps_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::MST_Position::inital_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba0fbfca81c6cac39788bbb65f584f05";
  }

  static const char* value(const  ::MST_Position::inital_gps_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xba0fbfca81c6cac3ULL;
  static const uint64_t static_value2 = 0x9788bbb65f584f05ULL;
};

template<class ContainerAllocator>
struct DataType< ::MST_Position::inital_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MST_Position/inital_gps";
  }

  static const char* value(const  ::MST_Position::inital_gps_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::MST_Position::inital_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64     target_heading\n\
float64     distance\n\
float64     waypoint\n\
\n\
";
  }

  static const char* value(const  ::MST_Position::inital_gps_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::MST_Position::inital_gps_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::MST_Position::inital_gps_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.target_heading);
    stream.next(m.distance);
    stream.next(m.waypoint);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct inital_gps_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MST_Position::inital_gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::MST_Position::inital_gps_<ContainerAllocator> & v) 
  {
    s << indent << "target_heading: ";
    Printer<double>::stream(s, indent + "  ", v.target_heading);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "waypoint: ";
    Printer<double>::stream(s, indent + "  ", v.waypoint);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MST_POSITION_MESSAGE_INITAL_GPS_H

