## *********************************************************
## 
## File autogenerated for the mst_color package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

##**********************************************************
## Software License Agreement (BSD License)
##
##  Copyright (c) 2008, Willow Garage, Inc.
##  All rights reserved.
##
##  Redistribution and use in source and binary forms, with or without
##  modification, are permitted provided that the following conditions
##  are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##   * Neither the name of the Willow Garage nor the names of its
##     contributors may be used to endorse or promote products derived
##     from this software without specific prior written permission.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
##  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
##  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
##  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
##  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
##  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
##  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
##  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
##  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##  POSSIBILITY OF SUCH DAMAGE.
##**********************************************************/

config_description = [{'srcline': 22, 'description': 'The size value of the sobel filter slope finder', 'max': 7, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/color.cfg', 'name': 'sobel_size', 'edit_method': "{'enum_description': 'Size of sobel filter', 'enum': [{'srcline': 15, 'description': 'A 3x1 filter with no Gaussinan smoothing', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': '3x1'}, {'srcline': 16, 'description': 'A 3x3 sobel filter', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': '3x3'}, {'srcline': 17, 'description': 'A 5x5 sobel filter', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': '5x5'}, {'srcline': 18, 'description': 'A 7x7 sobel filter', 'srcfile': '../cfg/color.cfg', 'cconsttype': 'const int', 'value': 7, 'ctype': 'int', 'type': 'int', 'name': '7x7'}]}", 'default': 3, 'level': 0, 'min': -1, 'type': 'int'}, {'srcline': 23, 'description': 'Value of the sobel filter order', 'max': 2, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/color.cfg', 'name': 'sobel_order', 'edit_method': '', 'default': 1, 'level': 0, 'min': 1, 'type': 'int'}, {'srcline': 24, 'description': 'Value multiplied to sobel', 'max': 300.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/color.cfg', 'name': 'sobel_scaler', 'edit_method': '', 'default': 1.0, 'level': 0, 'min': 1.0, 'type': 'double'}, {'srcline': 25, 'description': 'Value for maximum change in slope', 'max': 300.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/color.cfg', 'name': 'slope_var_thresh', 'edit_method': '', 'default': 1.0, 'level': 0, 'min': 1.0, 'type': 'double'}]

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

for param in config_description:
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

color_Params_3x1 = 1
color_Params_3x3 = 3
color_Params_5x5 = 5
color_Params_7x7 = 7
