//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the mst_homography package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __mst_homography__HOMOGRAPHY_PARAMSCONFIG_H__
#define __mst_homography__HOMOGRAPHY_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace mst_homography
{
  class homography_ParamsConfigStatics;
  
  class homography_ParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(homography_ParamsConfig &config, const homography_ParamsConfig &max, const homography_ParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const homography_ParamsConfig &config1, const homography_ParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, homography_ParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const homography_ParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, homography_ParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const homography_ParamsConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T homography_ParamsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (homography_ParamsConfig::* field);

      virtual void clamp(homography_ParamsConfig &config, const homography_ParamsConfig &max, const homography_ParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const homography_ParamsConfig &config1, const homography_ParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, homography_ParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const homography_ParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, homography_ParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const homography_ParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 14 "../cfg/homography_Params.cfg"
      std::string frame_id;
//#line 15 "../cfg/homography_Params.cfg"
      bool use_trans;
//#line 16 "../cfg/homography_Params.cfg"
      double theta_x;
//#line 17 "../cfg/homography_Params.cfg"
      double theta_y;
//#line 18 "../cfg/homography_Params.cfg"
      double theta_z;
//#line 19 "../cfg/homography_Params.cfg"
      double center_x;
//#line 20 "../cfg/homography_Params.cfg"
      double center_y;
//#line 22 "../cfg/homography_Params.cfg"
      int scale;
//#line 24 "../cfg/homography_Params.cfg"
      std::string laser_frame;
//#line 25 "../cfg/homography_Params.cfg"
      double laser_angle;
//#line 26 "../cfg/homography_Params.cfg"
      int laser_scans;
//#line 27 "../cfg/homography_Params.cfg"
      double laser_range_min;
//#line 28 "../cfg/homography_Params.cfg"
      double laser_range_max;
//#line 29 "../cfg/homography_Params.cfg"
      int laser_res;
//#line 30 "../cfg/homography_Params.cfg"
      double laser_time_increment;
//#line 31 "../cfg/homography_Params.cfg"
      double laser_scan_time;
//#line 32 "../cfg/homography_Params.cfg"
      int window_size;
//#line 33 "../cfg/homography_Params.cfg"
      double laser_threshold;
//#line 35 "../cfg/homography_Params.cfg"
      double pixels_per_meter;
//#line 36 "../cfg/homography_Params.cfg"
      double calibration_height;
//#line 37 "../cfg/homography_Params.cfg"
      double calibration_width;
//#line 38 "../cfg/homography_Params.cfg"
      double calibration_x;
//#line 39 "../cfg/homography_Params.cfg"
      double calibration_y;
//#line 42 "../cfg/homography_Params.cfg"
      int robot_x;
//#line 43 "../cfg/homography_Params.cfg"
      int robot_y;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("homography_ParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const homography_ParamsConfig &__max__ = __getMax__();
      const homography_ParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const homography_ParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const homography_ParamsConfig &__getDefault__();
    static const homography_ParamsConfig &__getMax__();
    static const homography_ParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const homography_ParamsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void homography_ParamsConfig::ParamDescription<std::string>::clamp(homography_ParamsConfig &config, const homography_ParamsConfig &max, const homography_ParamsConfig &min) const
  {
    return;
  }

  class homography_ParamsConfigStatics
  {
    friend class homography_ParamsConfig;
    
    homography_ParamsConfigStatics()
    {
//#line 14 "../cfg/homography_Params.cfg"
      __min__.frame_id = "";
//#line 14 "../cfg/homography_Params.cfg"
      __max__.frame_id = "";
//#line 14 "../cfg/homography_Params.cfg"
      __default__.frame_id = "/base_footprint";
//#line 14 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<std::string>("frame_id", "str", 1, "The base footprint of the robot", "", &homography_ParamsConfig::frame_id)));
//#line 15 "../cfg/homography_Params.cfg"
      __min__.use_trans = 0;
//#line 15 "../cfg/homography_Params.cfg"
      __max__.use_trans = 1;
//#line 15 "../cfg/homography_Params.cfg"
      __default__.use_trans = 0;
//#line 15 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<bool>("use_trans", "bool", 1, "option to use tf to find angle", "", &homography_ParamsConfig::use_trans)));
//#line 16 "../cfg/homography_Params.cfg"
      __min__.theta_x = -0.01;
//#line 16 "../cfg/homography_Params.cfg"
      __max__.theta_x = 0.01;
//#line 16 "../cfg/homography_Params.cfg"
      __default__.theta_x = 0.0;
//#line 16 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("theta_x", "double", 1, "camera rotation aplied to perspective.", "", &homography_ParamsConfig::theta_x)));
//#line 17 "../cfg/homography_Params.cfg"
      __min__.theta_y = -0.01;
//#line 17 "../cfg/homography_Params.cfg"
      __max__.theta_y = 0.01;
//#line 17 "../cfg/homography_Params.cfg"
      __default__.theta_y = 0.0;
//#line 17 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("theta_y", "double", 1, "camera rotation aplied to perspective.", "", &homography_ParamsConfig::theta_y)));
//#line 18 "../cfg/homography_Params.cfg"
      __min__.theta_z = -3.14159265359;
//#line 18 "../cfg/homography_Params.cfg"
      __max__.theta_z = 3.14159265359;
//#line 18 "../cfg/homography_Params.cfg"
      __default__.theta_z = 0.0;
//#line 18 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("theta_z", "double", 1, "camera rotation aplied to perspective.", "", &homography_ParamsConfig::theta_z)));
//#line 19 "../cfg/homography_Params.cfg"
      __min__.center_x = 0.0;
//#line 19 "../cfg/homography_Params.cfg"
      __max__.center_x = 360.0;
//#line 19 "../cfg/homography_Params.cfg"
      __default__.center_x = 0.0;
//#line 19 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("center_x", "double", 1, "center rotation is aplied on.", "", &homography_ParamsConfig::center_x)));
//#line 20 "../cfg/homography_Params.cfg"
      __min__.center_y = 0.0;
//#line 20 "../cfg/homography_Params.cfg"
      __max__.center_y = 480.0;
//#line 20 "../cfg/homography_Params.cfg"
      __default__.center_y = 0.0;
//#line 20 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("center_y", "double", 1, "center rotation is aplied on.", "", &homography_ParamsConfig::center_y)));
//#line 22 "../cfg/homography_Params.cfg"
      __min__.scale = 0;
//#line 22 "../cfg/homography_Params.cfg"
      __max__.scale = 10;
//#line 22 "../cfg/homography_Params.cfg"
      __default__.scale = 0;
//#line 22 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<int>("scale", "int", 1, "scale applied to the transform", "", &homography_ParamsConfig::scale)));
//#line 24 "../cfg/homography_Params.cfg"
      __min__.laser_frame = "";
//#line 24 "../cfg/homography_Params.cfg"
      __max__.laser_frame = "";
//#line 24 "../cfg/homography_Params.cfg"
      __default__.laser_frame = "bob";
//#line 24 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<std::string>("laser_frame", "str", 1, "name of the laser frame", "", &homography_ParamsConfig::laser_frame)));
//#line 25 "../cfg/homography_Params.cfg"
      __min__.laser_angle = 0.0;
//#line 25 "../cfg/homography_Params.cfg"
      __max__.laser_angle = 3.14159265359;
//#line 25 "../cfg/homography_Params.cfg"
      __default__.laser_angle = 3.14159265359;
//#line 25 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("laser_angle", "double", 1, "angle through wich the scan searches in rad", "", &homography_ParamsConfig::laser_angle)));
//#line 26 "../cfg/homography_Params.cfg"
      __min__.laser_scans = 0;
//#line 26 "../cfg/homography_Params.cfg"
      __max__.laser_scans = 360;
//#line 26 "../cfg/homography_Params.cfg"
      __default__.laser_scans = 180;
//#line 26 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<int>("laser_scans", "int", 1, "number of scans to preform", "", &homography_ParamsConfig::laser_scans)));
//#line 27 "../cfg/homography_Params.cfg"
      __min__.laser_range_min = 0.0;
//#line 27 "../cfg/homography_Params.cfg"
      __max__.laser_range_min = 30.0;
//#line 27 "../cfg/homography_Params.cfg"
      __default__.laser_range_min = 0.5;
//#line 27 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("laser_range_min", "double", 1, "The search radius of the laser in m.", "", &homography_ParamsConfig::laser_range_min)));
//#line 28 "../cfg/homography_Params.cfg"
      __min__.laser_range_max = 0.0;
//#line 28 "../cfg/homography_Params.cfg"
      __max__.laser_range_max = 30.0;
//#line 28 "../cfg/homography_Params.cfg"
      __default__.laser_range_max = 10.0;
//#line 28 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("laser_range_max", "double", 1, "The search radius of the laser in m.", "", &homography_ParamsConfig::laser_range_max)));
//#line 29 "../cfg/homography_Params.cfg"
      __min__.laser_res = 1;
//#line 29 "../cfg/homography_Params.cfg"
      __max__.laser_res = 360;
//#line 29 "../cfg/homography_Params.cfg"
      __default__.laser_res = 180;
//#line 29 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<int>("laser_res", "int", 1, "The search  degrees of laser", "", &homography_ParamsConfig::laser_res)));
//#line 30 "../cfg/homography_Params.cfg"
      __min__.laser_time_increment = 0.0;
//#line 30 "../cfg/homography_Params.cfg"
      __max__.laser_time_increment = 30.0;
//#line 30 "../cfg/homography_Params.cfg"
      __default__.laser_time_increment = 0.0;
//#line 30 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("laser_time_increment", "double", 1, "the increment time increment of the laser in sec", "", &homography_ParamsConfig::laser_time_increment)));
//#line 31 "../cfg/homography_Params.cfg"
      __min__.laser_scan_time = 0.0;
//#line 31 "../cfg/homography_Params.cfg"
      __max__.laser_scan_time = 30.0;
//#line 31 "../cfg/homography_Params.cfg"
      __default__.laser_scan_time = 0.0;
//#line 31 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("laser_scan_time", "double", 1, "the scan time increment of the laser in sec", "", &homography_ParamsConfig::laser_scan_time)));
//#line 32 "../cfg/homography_Params.cfg"
      __min__.window_size = 1;
//#line 32 "../cfg/homography_Params.cfg"
      __max__.window_size = 50;
//#line 32 "../cfg/homography_Params.cfg"
      __default__.window_size = 8;
//#line 32 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<int>("window_size", "int", 1, "The number of pixels to average for the threshold", "", &homography_ParamsConfig::window_size)));
//#line 33 "../cfg/homography_Params.cfg"
      __min__.laser_threshold = 0.0;
//#line 33 "../cfg/homography_Params.cfg"
      __max__.laser_threshold = 500.0;
//#line 33 "../cfg/homography_Params.cfg"
      __default__.laser_threshold = 200.0;
//#line 33 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("laser_threshold", "double", 1, "the threshold to qulify as obsticale", "", &homography_ParamsConfig::laser_threshold)));
//#line 35 "../cfg/homography_Params.cfg"
      __min__.pixels_per_meter = 0.0001;
//#line 35 "../cfg/homography_Params.cfg"
      __max__.pixels_per_meter = 300.0;
//#line 35 "../cfg/homography_Params.cfg"
      __default__.pixels_per_meter = 20.0;
//#line 35 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("pixels_per_meter", "double", 1, "number of pixels per meter", "", &homography_ParamsConfig::pixels_per_meter)));
//#line 36 "../cfg/homography_Params.cfg"
      __min__.calibration_height = 0.0001;
//#line 36 "../cfg/homography_Params.cfg"
      __max__.calibration_height = 300.0;
//#line 36 "../cfg/homography_Params.cfg"
      __default__.calibration_height = 1.0;
//#line 36 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("calibration_height", "double", 1, "height of the calibration square in meters", "", &homography_ParamsConfig::calibration_height)));
//#line 37 "../cfg/homography_Params.cfg"
      __min__.calibration_width = 0.0001;
//#line 37 "../cfg/homography_Params.cfg"
      __max__.calibration_width = 300.0;
//#line 37 "../cfg/homography_Params.cfg"
      __default__.calibration_width = 1.0;
//#line 37 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("calibration_width", "double", 1, "width of the calibration square in meters", "", &homography_ParamsConfig::calibration_width)));
//#line 38 "../cfg/homography_Params.cfg"
      __min__.calibration_x = 0.0001;
//#line 38 "../cfg/homography_Params.cfg"
      __max__.calibration_x = 300.0;
//#line 38 "../cfg/homography_Params.cfg"
      __default__.calibration_x = 1.0;
//#line 38 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("calibration_x", "double", 1, "distance to botom center  in meters", "", &homography_ParamsConfig::calibration_x)));
//#line 39 "../cfg/homography_Params.cfg"
      __min__.calibration_y = 0.0001;
//#line 39 "../cfg/homography_Params.cfg"
      __max__.calibration_y = 300.0;
//#line 39 "../cfg/homography_Params.cfg"
      __default__.calibration_y = 1.0;
//#line 39 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<double>("calibration_y", "double", 1, "distance to bottom center in meters", "", &homography_ParamsConfig::calibration_y)));
//#line 42 "../cfg/homography_Params.cfg"
      __min__.robot_x = 0;
//#line 42 "../cfg/homography_Params.cfg"
      __max__.robot_x = 400;
//#line 42 "../cfg/homography_Params.cfg"
      __default__.robot_x = 200;
//#line 42 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<int>("robot_x", "int", 1, "The height of the robot mask.", "", &homography_ParamsConfig::robot_x)));
//#line 43 "../cfg/homography_Params.cfg"
      __min__.robot_y = 0;
//#line 43 "../cfg/homography_Params.cfg"
      __max__.robot_y = 400;
//#line 43 "../cfg/homography_Params.cfg"
      __default__.robot_y = 100;
//#line 43 "../cfg/homography_Params.cfg"
      __param_descriptions__.push_back(homography_ParamsConfig::AbstractParamDescriptionConstPtr(new homography_ParamsConfig::ParamDescription<int>("robot_y", "int", 1, "The width of the robot mask.", "", &homography_ParamsConfig::robot_y)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<homography_ParamsConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<homography_ParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    homography_ParamsConfig __max__;
    homography_ParamsConfig __min__;
    homography_ParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const homography_ParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static homography_ParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &homography_ParamsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const homography_ParamsConfig &homography_ParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const homography_ParamsConfig &homography_ParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const homography_ParamsConfig &homography_ParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<homography_ParamsConfig::AbstractParamDescriptionConstPtr> &homography_ParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const homography_ParamsConfigStatics *homography_ParamsConfig::__get_statics__()
  {
    const static homography_ParamsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = homography_ParamsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __HOMOGRAPHY_PARAMSRECONFIGURATOR_H__
