## *********************************************************
## 
## File autogenerated for the MST_ColorStat package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

##**********************************************************
## Software License Agreement (BSD License)
##
##  Copyright (c) 2008, Willow Garage, Inc.
##  All rights reserved.
##
##  Redistribution and use in source and binary forms, with or without
##  modification, are permitted provided that the following conditions
##  are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##   * Neither the name of the Willow Garage nor the names of its
##     contributors may be used to endorse or promote products derived
##     from this software without specific prior written permission.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
##  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
##  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
##  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
##  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
##  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
##  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
##  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
##  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##  POSSIBILITY OF SUCH DAMAGE.
##**********************************************************/

config_description = [{'srcline': 14, 'description': 'Reset statistics each frame.', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '../cfg/ColorStat_Params.cfg', 'name': 'reset', 'edit_method': '', 'default': False, 'level': 1, 'min': False, 'type': 'bool'}, {'srcline': 15, 'description': 'Statistics gathering enabled.', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '../cfg/ColorStat_Params.cfg', 'name': 'enabled', 'edit_method': '', 'default': False, 'level': 1, 'min': False, 'type': 'bool'}, {'srcline': 16, 'description': 'xMin of statistics gathering box.', 'max': 640, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/ColorStat_Params.cfg', 'name': 'xMin', 'edit_method': '', 'default': 270, 'level': 1, 'min': 0, 'type': 'int'}, {'srcline': 17, 'description': 'xMax of statistics gathering box.', 'max': 640, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/ColorStat_Params.cfg', 'name': 'xMax', 'edit_method': '', 'default': 370, 'level': 1, 'min': 0, 'type': 'int'}, {'srcline': 18, 'description': 'yMin of statistics gathering box.', 'max': 480, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/ColorStat_Params.cfg', 'name': 'yMin', 'edit_method': '', 'default': 0, 'level': 1, 'min': 0, 'type': 'int'}, {'srcline': 19, 'description': 'yMax of statistics gathering box.', 'max': 480, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '../cfg/ColorStat_Params.cfg', 'name': 'yMax', 'edit_method': '', 'default': 100, 'level': 1, 'min': 0, 'type': 'int'}]

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

for param in config_description:
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

