/* Auto-generated by genmsg_cpp for file /home/sean/ros_workspace/joe_controller_pkg/srv/ApplyJointEffort.srv */
#ifndef JOE_CONTROLLER_PKG_SERVICE_APPLYJOINTEFFORT_H
#define JOE_CONTROLLER_PKG_SERVICE_APPLYJOINTEFFORT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace joe_controller_pkg
{
template <class ContainerAllocator>
struct ApplyJointEffortRequest_ : public ros::Message
{
  typedef ApplyJointEffortRequest_<ContainerAllocator> Type;

  ApplyJointEffortRequest_()
  : joint_name()
  , effort(0.0)
  , start_time()
  , duration()
  {
  }

  ApplyJointEffortRequest_(const ContainerAllocator& _alloc)
  : joint_name(_alloc)
  , effort(0.0)
  , start_time()
  , duration()
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  joint_name;

  typedef double _effort_type;
  double effort;

  typedef ros::Time _start_time_type;
  ros::Time start_time;

  typedef ros::Duration _duration_type;
  ros::Duration duration;


private:
  static const char* __s_getDataType_() { return "joe_controller_pkg/ApplyJointEffortRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2c3396ab9af67a509ecd2167a8fe41a2"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c0039811b8cc919490b3cff748cdf46b"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
string joint_name\n\
float64 effort\n\
time start_time\n\
\n\
duration duration\n\
\n\
\n\
\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, joint_name);
    ros::serialization::serialize(stream, effort);
    ros::serialization::serialize(stream, start_time);
    ros::serialization::serialize(stream, duration);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, joint_name);
    ros::serialization::deserialize(stream, effort);
    ros::serialization::deserialize(stream, start_time);
    ros::serialization::deserialize(stream, duration);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(joint_name);
    size += ros::serialization::serializationLength(effort);
    size += ros::serialization::serializationLength(start_time);
    size += ros::serialization::serializationLength(duration);
    return size;
  }

  typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct ApplyJointEffortRequest
typedef  ::joe_controller_pkg::ApplyJointEffortRequest_<std::allocator<void> > ApplyJointEffortRequest;

typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortRequest> ApplyJointEffortRequestPtr;
typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortRequest const> ApplyJointEffortRequestConstPtr;


template <class ContainerAllocator>
struct ApplyJointEffortResponse_ : public ros::Message
{
  typedef ApplyJointEffortResponse_<ContainerAllocator> Type;

  ApplyJointEffortResponse_()
  : success(false)
  , status_message()
  {
  }

  ApplyJointEffortResponse_(const ContainerAllocator& _alloc)
  : success(false)
  , status_message(_alloc)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  status_message;


private:
  static const char* __s_getDataType_() { return "joe_controller_pkg/ApplyJointEffortResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2ec6f3eff0161f4257b808b12bc830c2"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c0039811b8cc919490b3cff748cdf46b"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
string status_message\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    ros::serialization::serialize(stream, status_message);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    ros::serialization::deserialize(stream, status_message);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    size += ros::serialization::serializationLength(status_message);
    return size;
  }

  typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct ApplyJointEffortResponse
typedef  ::joe_controller_pkg::ApplyJointEffortResponse_<std::allocator<void> > ApplyJointEffortResponse;

typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortResponse> ApplyJointEffortResponsePtr;
typedef boost::shared_ptr< ::joe_controller_pkg::ApplyJointEffortResponse const> ApplyJointEffortResponseConstPtr;

struct ApplyJointEffort
{

typedef ApplyJointEffortRequest Request;
typedef ApplyJointEffortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ApplyJointEffort
} // namespace joe_controller_pkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2c3396ab9af67a509ecd2167a8fe41a2";
  }

  static const char* value(const  ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2c3396ab9af67a50ULL;
  static const uint64_t static_value2 = 0x9ecd2167a8fe41a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "joe_controller_pkg/ApplyJointEffortRequest";
  }

  static const char* value(const  ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
string joint_name\n\
float64 effort\n\
time start_time\n\
\n\
duration duration\n\
\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const  ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "joe_controller_pkg/ApplyJointEffortResponse";
  }

  static const char* value(const  ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
string status_message\n\
\n\
\n\
";
  }

  static const char* value(const  ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint_name);
    stream.next(m.effort);
    stream.next(m.start_time);
    stream.next(m.duration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ApplyJointEffortRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
    stream.next(m.status_message);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ApplyJointEffortResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<joe_controller_pkg::ApplyJointEffort> {
  static const char* value() 
  {
    return "c0039811b8cc919490b3cff748cdf46b";
  }

  static const char* value(const joe_controller_pkg::ApplyJointEffort&) { return value(); } 
};

template<>
struct DataType<joe_controller_pkg::ApplyJointEffort> {
  static const char* value() 
  {
    return "joe_controller_pkg/ApplyJointEffort";
  }

  static const char* value(const joe_controller_pkg::ApplyJointEffort&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0039811b8cc919490b3cff748cdf46b";
  }

  static const char* value(const joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "joe_controller_pkg/ApplyJointEffort";
  }

  static const char* value(const joe_controller_pkg::ApplyJointEffortRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0039811b8cc919490b3cff748cdf46b";
  }

  static const char* value(const joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "joe_controller_pkg/ApplyJointEffort";
  }

  static const char* value(const joe_controller_pkg::ApplyJointEffortResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // JOE_CONTROLLER_PKG_SERVICE_APPLYJOINTEFFORT_H

