<?xml version="1.0"?>
<robot name="jomegatron"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" >

    <!-- all values are in inches and are converted to meters bellow -->
    <property name="pi" value="3.1415"/>
    <property name="in_m" value="0.0254"/>
    
    <property name="base_width" value="28"/>
    <property name="base_length" value="40"/>
    <property name="base_height" value="24"/>
    <property name="base_clearance" value="9.5"/>
    
    <property name="wheel_radius" value="8"/>
    <property name="wheel_width" value="5"/>
    <property name="wheel_setback" value="10"/>
    <property name="wheel_block_height" value="1.5"/>
    <property name="wheel_separation" value="21"/>
    
    <property name="castor_bar_height" value="6"/>
    <property name="castor_bar_width" value="4"/>
    <property name="castor_bar_length" value="5"/>
    <property name="castor_bar_setback" value="25"/>
    
    <property name="castor_radius" value="3"/>
    <property name="castor_width" value="3"/>
    <property name="castor_radius" value="4"/>
    
    
    <property name="mast_base_height" value="12"/>
    <property name="mast_base_width" value="28"/>
    <property name="mast_base_length" value="1"/>
    <property name="mast_base_setback" value="13"/>
    
    <property name="mast_vertical_height" value="14"/>
    <property name="mast_vertical_width" value="1"/>
    <property name="mast_vertical_length" value="1"/>
    
    <property name="mast_horizontal_height" value="1"/>
    <property name="mast_horizontal_width" value="1"/>
    <property name="mast_horizontal_length" value="12"/>
    <property name="mast_horizontal_setback" value="8"/>
    
    <property name="camera_mount_height" value="3.5"/>
    <property name="camera_mount_width" value="3.5"/>
    <property name="camera_mount_length" value="1"/>
    <property name="camera_mount_setback" value="1"/>
    
    <property name="pt_grey_height" value="1.5"/>
    <property name="pt_grey_width" value="2"/>
    <property name="pt_grey_length" value="3"/>
    
    <property name="midg_height" value="1.5"/>
    <property name="midg_width" value="3"/>
    <property name="midg_length" value="4"/>
    <property name="midg_offset" value="2.5"/>
    
    
    
    


    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    
    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <material name="Grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    
    <material name="Shadow">
        <color rgba="0.25 0.25 0.25 1"/>
    </material>

    <!-- robot footprint -->
    <link name="base_footprint">
        <inertial>
          <mass value="0.0001" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} 0.001" />
            </geometry>
            <material name="Shadow" />
        </visual>

        <collision>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} 0.001" />
            </geometry>
        </collision>
    </link>
    
    
    <!-- robot base -->
    <link name="base_link">
        <inertial>
            <mass value="50" />
            <origin xyz="0 0 0.0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
            iyy="0.01" iyz="0.0" izz="0.5" />
        </inertial>

        <visual>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 ${base_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} ${base_height*in_m}" />
            </geometry>
            <material name="Green" />
        </visual>

        <collision>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 ${base_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} ${base_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_clearance*in_m}" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>
    
    
    <!-- left wheel -->
    <link name="left_wheel_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="2" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 ${-wheel_separation/2*in_m} ${-wheel_block_height*in_m} " rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    
    <!-- right wheel -->
    <link name="right_wheel_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="2" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 ${wheel_separation/2*in_m} ${-wheel_block_height*in_m} " rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <!-- right castor bar -->
    <link name="right_castor_bar_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 ${-castor_bar_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${castor_bar_length*in_m} ${castor_bar_width*in_m} ${castor_bar_height*in_m}" />
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="0 0 ${-castor_bar_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${castor_bar_length*in_m} ${castor_bar_width*in_m} ${castor_bar_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="right_castor_bar_joint" type="fixed">
        <origin xyz="${-castor_bar_setback*in_m} ${wheel_separation/2*in_m} 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_castor_bar_link"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <!-- left castor bar -->
    <link name="left_castor_bar_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 ${-castor_bar_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${castor_bar_length*in_m} ${castor_bar_width*in_m} ${castor_bar_height*in_m}" />
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="0 0 ${-castor_bar_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${castor_bar_length*in_m} ${castor_bar_width*in_m} ${castor_bar_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="left_castor_bar_joint" type="fixed">
        <origin xyz="${-castor_bar_setback*in_m} ${-wheel_separation/2*in_m} 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_castor_bar_link"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- right castor -->
    <link name="right_castor_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="2" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${castor_radius*in_m}" length = "${castor_width*in_m}"/>
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${castor_radius*in_m}" length = "${castor_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="right_castor_joint" type="fixed">
        <origin xyz="0 0 ${(.5-castor_bar_height)*in_m} " rpy="0 0 0"/>
        <parent link="right_castor_bar_link"/>
        <child link="right_castor_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <!-- left castor -->
    <link name="left_castor_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="2" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${castor_radius*in_m}" length = "${castor_width*in_m}"/>
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${castor_radius*in_m}" length = "${castor_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="left_castor_joint" type="fixed">
        <origin xyz="0 0 ${(.5-castor_bar_height)*in_m} " rpy="0 0 0"/>
        <parent link="left_castor_bar_link"/>
        <child link="left_castor_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <!-- mast base -->
    <link name="mast_base_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 ${(mast_base_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${mast_base_length*in_m} ${mast_base_width*in_m} ${mast_base_height*in_m}" />
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="0 0 ${(mast_base_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${mast_base_length*in_m} ${mast_base_width*in_m} ${mast_base_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="mast_base_joint" type="fixed">
        <origin xyz="${-mast_base_setback*in_m} 0 ${base_height*in_m}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="mast_base_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <!-- midg -->
    <link name="midg_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 ${(midg_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${midg_length*in_m} ${midg_width*in_m} ${midg_height*in_m}" />
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 ${(midg_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${midg_length*in_m} ${midg_width*in_m} ${midg_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="midg_joint" type="fixed">
        <origin xyz="0 ${-midg_offset * in_m} ${mast_base_height*in_m}" rpy="0 0 ${-pi/2}"/>
        <parent link="mast_base_link"/>
        <child link="midg_link"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <!-- mast vertical -->
    <link name="mast_vertical_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 ${(mast_vertical_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${mast_vertical_length*in_m} ${mast_vertical_width*in_m} ${mast_vertical_height*in_m}" />
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="0 0 ${(mast_vertical_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${mast_vertical_length*in_m} ${mast_vertical_width*in_m} ${mast_vertical_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="mast_vertical_joint" type="fixed">
        <origin xyz="0 0 ${mast_base_height*in_m}" rpy="0 0 0"/>
        <parent link="mast_base_link"/>
        <child link="mast_vertical_link"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <!-- mast horizontal -->
    <link name="mast_horizontal_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="${(mast_horizontal_setback - (mast_horizontal_length/2))*in_m} 0 ${mast_horizontal_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${mast_horizontal_length*in_m} ${mast_horizontal_width*in_m} ${mast_horizontal_height*in_m}" />
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="${(mast_horizontal_setback - (mast_horizontal_length/2))*in_m} 0 ${mast_horizontal_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${mast_horizontal_length*in_m} ${mast_horizontal_width*in_m} ${mast_horizontal_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="mast_horizontal_joint" type="fixed">
        <origin xyz="0 0 ${mast_vertical_height*in_m}" rpy="0 0 0"/>
        <parent link="mast_vertical_link"/>
        <child link="mast_horizontal_link"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <!-- camera mount -->
    <link name="camera_mount_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".3" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 ${-((camera_mount_height/2)-0.5)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${camera_mount_length*in_m} ${camera_mount_width*in_m} ${camera_mount_height*in_m}" />
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="0 0 ${-((camera_mount_height/2)-0.5)*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${camera_mount_length*in_m} ${camera_mount_width*in_m} ${camera_mount_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="camera_mount_joint" type="fixed">
        <origin xyz="${(mast_horizontal_setback-camera_mount_setback)*in_m} 0 ${mast_horizontal_height/2*in_m}" rpy="0 0 0"/>
        <parent link="mast_horizontal_link"/>
        <child link="camera_mount_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <!-- pt_grey -->
    <link name="pt_grey_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".3" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${pt_grey_length*in_m} ${pt_grey_width*in_m} ${pt_grey_height*in_m}" />
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${pt_grey_length*in_m} ${pt_grey_width*in_m} ${pt_grey_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="pt_grey_joint" type="continuous">
        <origin xyz="0 0 ${-(camera_mount_height-1)*in_m}" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_mount_link"/>
        <child link="pt_grey_link"/>
        <axis xyz="1 0 0"/>
    </joint>

</robot>
